language: cpp
sudo: required
dist: xenial
os:
  - linux

services:
  - docker

env:
  - IMPL=COMPUTECPP CXX_COMPILER=g++-7 CC_COMPILER=gcc-7 TARGET=opencl
  - IMPL=COMPUTECPP CXX_COMPILER=clang++-5.0 CC_COMPILER=clang-5.0 TARGET=opencl

matrix:
  fast_finish: true

before_install:
  - |
    if [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then
       export GIT_SLUG=${TRAVIS_REPO_SLUG}
       export GIT_BRANCH=${TRAVIS_BRANCH}
    else
       export GIT_SLUG=${TRAVIS_PULL_REQUEST_SLUG}
       export GIT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}
    fi
  - docker build --build-arg c_compiler=${CC_COMPILER}
                 --build-arg cxx_compiler=${CXX_COMPILER}
                 --build-arg git_branch=${GIT_BRANCH}
                 --build-arg git_slug=${GIT_SLUG}
                 --build-arg impl=${IMPL}
                 --build-arg target=${TARGET}
                 -t sycl-dnn .

script:
  - docker run sycl-dnn 
